### ISSUE TITLE
'comb' from 'scipy.misc' is deprecated

### ISSUE THREAD

**Issue by ykarrer** [jbkinney/suftware#10]
If I want to import suftware in python, I get the following import error:
"cannot import name 'comb' from 'scipy.misc'"
...apparently, 'comb' is deprecated (see also documentation of scipy)

Is there a way how I can still use suftware, altough I'm using the newer scipy version?

**Comment by atareen** [comment]
Hello ykarrer,

Thanks for bringing this to our attention. An updated version of suftware will be deployed next week to fix this comb issue.

In the meantime, here are some alternatives that should temporarily get suftware working until the new release:

1) use 'virtualenv'; this python package will let you use suftware with an older version of comb without affecting your system installation of scipy.

2) you can use suftware on google colab with python 2.7. Since google colab packages are hosted online, you can install any package you want (e.g. an older version of scipy to get suftware running) and it should not affect you system's python.

3) Suftware's behavior is the same for python 2.7 and 3.6. As a temporary solution, you could use suftware with python 2 (if previously you were use python 3) with an older version of scipy?

Thanks again,
Ammar

**Comment by ykarrer** [comment]
Perfect, thanks a lot!!

**Comment by atareen** [comment]
Hey @ykarrer, I just released suftware 0.15 which contains the fix for this comb issue. Please update your suftware via pip and let me know if you still have the issue. 

Thanks!
-Ammar

**Comment by ykarrer** [comment]
Works perfectly fine now. Thanks!
